 # Informations de base sur le projet
 sonar.projectKey=mon-projet-flask
 sonar.projectName=Mon Projet Flask
 sonar.projectVersion=1.0

 # Chemin relatif au fichier sonar-project.properties
 sonar.sources=.

 # Encodage des fichiers sources
 sonar.sourceEncoding=UTF-8

 # URL du serveur SonarQube
 sonar.host.url=http://localhost:9000

 # Token d'authentification (remplace 'your_token' par ton token réel)
 sonar.login=your_token
 ```

